name: inspectable_property
description: "Improve your classes with reflection capabilities. Use a visual inspector to read/write inspectable properties."
version: 0.0.3
repository: https://github.com/rusoleal/inspectable_property

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sprintf: ^7.0.0
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - reflection
  - editor
